### ISSUE TITLE
Trying to get past the "Usage" section

### ISSUE THREAD

**Issue by AwesomeNoah** [spookyGh0st/beatwalls#12]
Hi, just started setting up beatwalls, and dragging a song folder (with mapping extensions) just brings up these errors. Any way you could assist is much appreciated! I couldn't find you on Discord, but my tag is awesomenoah#8627

https://imgur.com/a/YTZBWGn

**Comment by TheRedKorsar** [comment]
Check in Info.dat letter "i" must be uppercase to beatwalls works.
