### ISSUE TITLE
--deleteAllPrevious and --clearAll not deleting walls

### ISSUE THREAD

**Issue by Shadowolf50146** [spookyGh0st/beatwalls#16]
--deleteallprevious and --clearall arent deleting the existing walls in the map. i somehow made it work the very first time i ran the exe, but now it just wont work anymore.

i put it at the very top of the code
![heklpne](https://user-images.githubusercontent.com/70414844/96671462-6c815680-1327-11eb-91f1-e2b03fc53530.png)

ive tried:
deleteallprevious
deleteallprevious: true
--deleteallprevious
--deleteallprevious: true

**Comment by crmbz0r** [comment]
Try making a shortcut of the .exe on your desktop, then open its properties and put your -- commands behind the target (the upper one).
For example: 
"C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\beatwalls_o.exe" --deleteAllPrevious
