### ISSUE TITLE
world rotation bug

### ISSUE THREAD

**Issue by thelightdesigner** [spookyGh0st/beatwalls#18]
the newest version writes world rotation as an array with a single float. It should be either or.
![Screenshot_1](https://user-images.githubusercontent.com/48635344/102036574-2ed20480-3d91-11eb-9c51-8d2c7217c14a.jpg)

**Comment by spookyGh0st** [comment]
Hey, can you try out if the latest release fixes that?

**Comment by thelightdesigner** [comment]
It does
