### ISSUE TITLE
njs offset whitespace in json

### ISSUE THREAD

**Issue by thelightdesigner** [spookyGh0st/beatwalls#19]
tested in newest version
![Screenshot_1](https://user-images.githubusercontent.com/48635344/103390013-293e2380-4ae0-11eb-90f2-745c04faf60a.jpg)

**Comment by thelightdesigner** [comment]
been an issue for a long ass time but only opening now sorry

**Comment by spookyGh0st** [comment]
fixed, will be in the next release soonTM
