### ISSUE TITLE
[correct code] Correct example

### ISSUE THREAD

**Issue by MilkVio** [spookyGh0st/beatwalls#3]
In the last line of the **Defining you own structures** Example:
`define: tunnel
    structures: _tunnel1,_tunnel2,_tunnel3,tunnel4`
 
Should be corrected like:
`define: tunnel
    structures: _tunnel1,_tunnel2,_tunnel3,**_**tunnel4`
--------------------------------------------------------------------------------------------------------------
Then this example should also be corrected:
```
10: tunnel
12: tunnel
16.6: tunnel
# a tunnel, which is twice as long
20: tunel
    scale: 2
```

Should be corrected like:
```
10: tunnel
12: tunnel
16.6: tunnel
# a tunnel, which is twice as long
**20: tunnel**
    scale: 2
```

**Comment by spookyGh0st** [comment]
thanks! did not notice.
