### ISSUE TITLE
It can't find my map

### ISSUE THREAD

**Issue by NexyDeveloper** [spookyGh0st/beatwalls#44]
Whenever I open beatwalls it says "For the first setup please drag in the map folder! Could read directory C:\Users\(my name)\Downloads. Have you deleted the map?", how do I fix this.

**Comment by spookyGh0st** [comment]
Drag a Song Folder into the .exe to launch the configuration setup.
![Untitled](https://user-images.githubusercontent.com/49662302/170869481-93cd98b2-70f1-47b5-9424-3dc4f6f33492.png)
