### ISSUE TITLE
[Request] repeatAddRadius & repeatAddEndRadius

### ISSUE THREAD

**Issue by crmbz0r** [spookyGh0st/beatwalls#5]
Sorry I don't know how the pull requests thing works if this belongs there.. 

But as the title says, I'd love to get repeatAddRadius & repeatAddEndRadius added, for example to multiply the noodlehelix into various sizes without having to copy the whole thing everytime. I probably have a mess in my file anyways but that would shrink the size a bit. :P 

Edit: I just thought repeadAddScale and repeatAddAmount would be awesome too for the noodlehelix if possible. :D 

thx :)

**Comment by spookyGh0st** [comment]
> Sorry I don't know how the pull requests thing works if this belongs there..

Yep, this is perfect for it!

> But as the title says, I'd love to get repeatAddRadius & repeatAddEndRadius added.

I am currently reworking the syntax, and soon you will be able to repeat any property you want :)

**Comment by crmbz0r** [comment]
Awesome, I just had the thought of repeating any property today too, but then I thought that might be wanting too much. 
Absolutely can't wait to use it :)

**Comment by crmbz0r** [comment]
I see, it's finally here to try out :D 
Also I'd like to message you on discord, but I can't add you without the #0000 number behind your name..

**Comment by spookyGh0st** [comment]
hey, you can find me in the bsmg discord. https://discord.gg/beatsabermods just ping me there. Also note that this one still has some bugs and not all wallstructures are woking atm

**Comment by spookyGh0st** [comment]
closing this, since this is now fully working
