### ISSUE TITLE
Error Parsing line

### ISSUE THREAD

**Issue by NordKingGaming** [spookyGh0st/beatwalls#8]
hey man, on the new update when you first drop a file in it gives an error, its easily remedied by deleting that line or clearing the .bw file but I figured I would bring it to your attention. here is a link with a picture of the error. looking forward to trying this update. thanks again for all your hard work.

https://gyazo.com/a1d7749c863456b6eb1798ac61783e4e

**Comment by spookyGh0st** [comment]
Welp, this is a bit late :D but i finally got around to fixing that!
